### ISSUE TITLE
Add avatar photos

### ISSUE THREAD

**Issue by jpslav** [openstax/accounts#106]
Add support for avatar photos.

One `User` should be capable of storing one avatar photo.  Optionally, we could let a user store multiple avatars, but one should always be the active one.  If we allow multiple avatars, then every time an authentication is added we could just copy in that authenticator's profile pic to make it easy on the user, then the user could just select it.

If the user doesn't specify a photo, we should get gravatar to generate one for us based on the user's UUID, e.g. pass this URL to Gravatar:

```
http://www.gravatar.com/avatar/PUT_UUID_HERE?s=164&d=identicon&r=PG
```

Accounts should expose a URL that retrieves the profile pic at different sizes.  The user should be specified in the URL by her UUID, e.g.

```
https://accounts.openstax.org/user/UUID/avatar?s=24
```

Store profile pics in the following sizes: 24x24, 48x48, 128x128

The avatar URL doesn't need to be returned in search results if the UUID is (because then anyone can create the appropriate URL).

Use Carrierwave for uploading. Use rmagick for resizing.  OSC already has a JS form for uploading and cropping a profile picture (all working with Carrierwave and rmagick), start looking in https://github.com/lml/osc/tree/master/app/views/manage/headshots

We will want to store uploads in s3 probably using the fog gem.

**Comment by Dantemss** [comment]
OmniauthData now provides the image method that returns a user's profile image from google/fb/twitter.
