### ISSUE TITLE
Accounts issues observed on Dev May 11-12

### ISSUE THREAD

**Issue by brittanyearly** [openstax/accounts#1076]
- [x] Admin console button appears during sign up

![Screen Shot 2022-05-12 at 12.35.28 PM.png](https://images.zenhubusercontent.com/5e5d63c303758d16a213e50d/1ce7dbdb-b697-4a86-9f49-5f5a2c51e10e)

- [x] After Pin submission, page is blank 

![Screen Shot 2022-05-12 at 12.39.26 PM.png](https://images.zenhubusercontent.com/5e5d63c303758d16a213e50d/3b89b290-3416-49f1-99fa-1a7af203399f)
![Screen Shot 2022-05-12 at 12.40.56 PM.png](https://images.zenhubusercontent.com/5e5d63c303758d16a213e50d/5a76ae36-7464-48f6-8d53-863a2a372ba8)

- [x] Signing in to same account (from above) shows same blank page, even on incognito. URL is: https://dev.accounts.openstax.org/signup/educator/apply

- [x] Clearing /signup/educator/apply from URL brings user to /profile not homepage

- [x] When on profile, clicking to change name does not bring up a text field. Warns "first and last name cannot be blank".

![Screen Shot 2022-05-12 at 12.44.45 PM.png](https://images.zenhubusercontent.com/5e5d63c303758d16a213e50d/0c24a342-19a8-404d-a541-fab01ab3a2e8)
![Screen Shot 2022-05-12 at 12.46.08 PM.png](https://images.zenhubusercontent.com/5e5d63c303758d16a213e50d/b54267c3-b9c0-42d5-8277-a00ac46cd4ba)

- [x] Password reset link in email is broken (old URL): https://accounts-dev.openstax.org/change_password_form?token=a07158084186676c97de87d699bc1975

**Comment by RoyEJohnson** [comment]
> Clearing /signup/educator/apply from URL brings user to /profile not homepage

Use https://dev.openstax.org/accounts rather than https://dev.accounts.openstax.org
Nobody should really be going directly to accounts.openstax.org.

**Comment by RoyEJohnson** [comment]
> When on profile, clicking to change name does not bring up a text field. Warns "first and last name cannot be blank".

I see this on Dev, but not locally.

**Comment by mwvolo** [comment]
closing this in favor of other bug cards we have for v14-alpha and v14-beta.x
