### ISSUE TITLE
Unable to update user information

### ISSUE THREAD

**Issue by nathanstitt** [openstax/accounts#1107]
Whenever a user attempts to update their user name on accounts, a HTML 404 error is returned.  That HTML is then displayed inline under the form.

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/2e9fec8f-3adc-4c13-8e69-708efb74c296)

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/7ea067da-8213-4106-a2fb-f5efa003d236)

**Comment by Dantemss** [comment]
@nathanstitt I am able to edit my name on https://accounts.openstax.org/i/profile
What error are you seeing on the API call?

**Comment by nathanstitt** [comment]
weird! I'm seeing the same HTML appear with a 404 
<img width="680" alt="image" src="https://user-images.githubusercontent.com/79566/186185849-40e69cf9-c524-4d85-886a-a91442acc342.png">

**Comment by nathanstitt** [comment]
@Dantemss huh, so I forced refreshed and now it works fine.  I'm guessing chrome had it cached.  On the old tab I see it loaded `https://openstax.org/accounts/assets/application/index-497644ed47450b06f307b1c2db5a1715d02e12b8fbd8fba1abfc359908620d72.js` from disk cache, and after force refresh it loads: `https://accounts.openstax.org/accounts/assets/profile/index-8076435724b13890f16814ab3fc48dd15b93be6abc78f29a733d10ff86530121.js`

**Comment by Dantemss** [comment]
That is troubling... Does that mean https://openstax.org/accounts home page is cached?

**Comment by Dantemss** [comment]
The profile page seems to have `cache-control: no-cache, no-store` so not sure what happened to yours.

**Comment by nathanstitt** [comment]
I've left the "bad" tab open, it shows an expires of 20 aug 202**3**

<img width="977" alt="image" src="https://user-images.githubusercontent.com/79566/186242799-77863c8a-6c12-4222-bea9-dbe2669946a1.png">

**Comment by nathanstitt** [comment]
@Dantemss I dug into this some more and on the "bad" tab, we're loading 2 index.js scripts!  after force reload I only see on in the html.

Bad html heading (the 2nd script is 3 lines down from the highlighted line:
<img width="999" alt="image" src="https://user-images.githubusercontent.com/79566/186244411-1b4c568c-0ded-4192-aebc-6f63c6455580.png">

Good:
<img width="835" alt="image" src="https://user-images.githubusercontent.com/79566/186244530-6005888d-23ee-48e0-9448-572229e65553.png">

**Comment by nathanstitt** [comment]
@Dantemss I'm also seeing the same behavior on staging.  I haven't (yet) force reloaded there so we can debug if you'd like

**Comment by Dantemss** [comment]
The JS being cached forever is normal, but the html should not be cached

**Comment by nathanstitt** [comment]
well that's the strange thing, I don't think it is being cached.  Its unclear to me why it's delivering the incorrect JS script tag.  For instance on staging the HTML shows a miss from cloud front, and an expiration of 1990 so I dunno where it's coming from.

<img width="903" alt="image" src="https://user-images.githubusercontent.com/79566/186258578-ae253287-2c6f-4f62-b80d-e55c3191fca9.png">
