### ISSUE TITLE
Inconsistent Salesforce Contact state between Accounts and Salesforce

### ISSUE THREAD

**Issue by brittanyearly** [openstax/accounts#1139]
# Description
Some users were faculty verified in the past but seem to have lost their Contact and faculty status in Accounts, either due to duplicate accounts or due to them changing their email addresses.

**SCENARIO** _Briefly describe the issue._
The following users have Tutor courses, so they were likely faculty verified in the past but no longer.
Since the Contact is no longer linked to their Accounts, Tutor cannot send their courses' information to Salesforce.
They will also be prevented from creating new courses.

https://accounts.openstax.org/admin/users/972554/edit (duplicate account https://accounts.openstax.org/admin/users/574920/edit)
https://accounts.openstax.org/admin/users/114956/edit (duplicate account https://accounts.openstax.org/admin/users/144566/edit)
https://accounts.openstax.org/admin/users/407002/edit (no duplicate account)

----------------

**Steps to Reproduce the issue:** _Who, Where and How?_

**User Type:**
- [ ] Admin
- [ ] Content/QA
- [ ] Student
- [ ] Teacher
- [ ] All
- [ ] N/A

- **Username:**
- **URL:**  
- **Course number:**  
- **Course type:**

**Steps**
----------------
Possibly change email addresses in Accounts and/or Salesforce or create duplicate accounts.

**Environment:**

**Instance:**
- [ ] dev
- [ ] qa
- [ ] staging
- [x] production
- [ ] content
- [ ] demo

**OS:**
- [ ] Mac OSX
- [ ] Windows
- [ ] Android
- [ ] iOS
- [ ] All

**Browser:**
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Opera
- [ ] IE
- [ ] Edge

**Browser Version:**  

----------------
**Possible impact on a User:**
User can no longer create Tutor courses
User course information is not sent to Salesforce

----------------
**Expected Behavior:**
User Salesforce Contact information is not lost

----------------
**Images or Screenshots** (_attach below_)

# Approvals
1A-DEFINE
- [ ] PDM approves UX LoFi Design

1C-DESIGN
  - [ ] PDM approves UX HiFi Design

4A-UX REV
  - [ ] UX approves change
  - [ ] PDM approves change

# Process 
[Work Management for BIT](https://github.com/openstax/business-intel/blob/master/CONTRIBUTING.md)

**Comment by mwvolo** [comment]
Closing because of age/relevance. Let's open a new card for sync issues.
