### ISSUE TITLE
[Accounts] Pin screen Contact Us link broken on Sign Up

### ISSUE THREAD

**Issue by brittanyearly** [openstax/accounts#1162]
Description:
When Signing up, clicking the Link for Contact Us, under Pin text field, brings the user to a broken link. 
URL result: https://openstax.my.salesforce-sites.com/help/articles/FAQ/Can-t-log-in-to-your-OpenStax-account 
URL intended: https://help.openstax.org/s/article/Can-t-log-in-to-your-OpenStax-account (most likely)

Steps:
1. Go to staging.openstax.org
2. Click Login in Right Upper menu
3. Click Sign Up
4. Click Educator
5. Complete Step 1 form
6. Click Contact Us link on Step 2 form
7. Notice link directs you to a broken url

Screenshot:

![Image](https://user-images.githubusercontent.com/61707659/230173166-bb1a81a3-265f-4721-8472-7b5933da29c1.png)

**Comment by mwvolo** [comment]
I was able to fix this with a redirect in Salesforce - no code needed. Ready for verification.
