### ISSUE TITLE
Make email address mandatory for certain apps

### ISSUE THREAD

**Issue by karenc** [openstax/accounts#117]
Our app needs to send emails to users but some users may not have any email addresses linked to their accounts.  For example, if I log in using twitter, twitter doesn't give us an email address, the "create your account" form also doesn't have an email address field.  

See original ticket https://github.com/Connexions/cnx-authoring/issues/191

**Comment by reedstrm** [comment]
I've verified that the workaround of  "sign in w/ twitter, create account, go to profile, add address" does work, but it would be much better to do it from the 'complete your account' page. Esp., since we can't retrieve the email address from our app, to determine that it's missing and send them to profile.

**Comment by Dantemss** [comment]
Honestly, if CNX needs this and maybe tutor needs this, we might wanna make it always mandatory.

**Comment by Dantemss** [comment]
Or at least require 1 valid contact info (be it email or SMS or whatever)

**Comment by lakshmivyas** [comment]
@Dantemss / @reedstrm / @karenc - twitter apparently is days away from implementing(maybe just documenting?) this:
https://twittercommunity.com/t/how-to-get-email-from-twitter-user-using-oauthtokens/558/135
https://twittercommunity.com/t/how-to-get-email-from-twitter-user-using-oauthtokens/558/140.

My suggestion would be to wait for this - or remove twitter temporarily if launch date is fixed.

We can also try contacting twitter developer support to see if they will allow us to beta test / preview this feature.

**Comment by edwoodward** [comment]
@lakshmi We have a temporary workaround.  Users can set their email from 
their profile so it is possible.  We can wait to see what Twitter does 
and not hold up our release.

**Comment by Dantemss** [comment]
JP said we can't make it mandatory for all of Accounts, because some kids in Tutor might not have an email address.

So we do need to implement this per-app.

**Comment by jpslav** [comment]
Which we could maybe have Accounts help enforce via validations / preferences on the `ApplicationUser`.... @Dantemss thoughts on this?

**Comment by Dantemss** [comment]
I think it needs to be an interceptor (before_filter) on the doorkeeper authorization page (to redirect the user to the profile page and tell them to add an email address), plus another validation on the ContactInfos (to prevent deletion of your last verified CI after you authorize an app that requires a CI).

**Comment by Dantemss** [comment]
This has been done... emails are required.
