### ISSUE TITLE
Remove Tutor reference from Sign Up screen

### ISSUE THREAD

**Issue by brittanyearly** [openstax/accounts#1185]
Description:
When viewing the Sign Up screen, there is a mention of Tutor under Students. As this sunsets, we should begin removing it from places, and a conversation can be had to what should replace it. This card is WIP and will be updated more.

Steps:
1. Go to openstax.org
2. Click on Log in from the Top Menu
3. Click Sign up
4. Notice the reference to Tutor under Student

Screenshot:

![Image](https://github.com/openstax/accounts/assets/61707659/6721fe7c-d559-4dbc-b61b-5455468b8fed)

**Comment by mwvolo** [comment]
@erikayvonne Do you have any suggestions for the text under "Student", so we can remove the reference to Tutor?

**Comment by erikayvonne** [comment]
What about "Sign up for a Student account to create and save notes and highlights in OpenStax study materials."

cc @anthonypalmiotto wrt Tutor sunset plan

**Comment by anthonypalmiotto** [comment]
Thank you.  I think Erika's edits work well.
