### ISSUE TITLE
Add student count and usage to each book on educator profile form

### ISSUE THREAD

**Issue by mwvolo** [openstax/accounts#1187]
**Is your feature request related to a problem? Please describe.**
We are currently collecting student number and usage information on the [Adoption Form](https://openstax.org/adoption). We'd like to mimic this behavior on the accounts signup profile form.

**Describe the solution you'd like**
When an educator/instructor is signing up, the final profile form should ask similar per-book questions as the adoption form.
The form information should be sent to Salesforce in the [adoptionJSON field](https://github.com/openstax/accounts/blob/main/app/routines/newflow/create_salesforce_lead.rb#L56) (already being used to send the book and student number - see [here](https://github.com/openstax/accounts/blob/main/app/routines/newflow/create_salesforce_lead.rb#L130-L150)) using the following format:
```
adoption_json: {"Books":[{"name":"Microbiology","students":11,"howUsing":"As an optional/recommended textbook for my course"}, {"name":"University Physics","students":18,"howUsing":"As the core textbook for my course"}]}
```

**Additional context**
Screenshot of adoption form questions that we'd like duplicated on the accounts signup.
![image](https://github.com/openstax/accounts/assets/3905516/c7ee4c88-d9b2-4a51-89dc-7af32c1caaf7)

**Comment by mwvolo** [comment]
Hi, @jivey 👋 
I spoke with Tom and Erika about you maybe picking this up in the next couple weeks and they gave me their blessing. Please let me know if you have any questions or if your work priorities have shifted around!
Thanks!

**Comment by jivey** [comment]
@mwvolo Sounds good! I'll likely be able to pick this up next week 👍

**Comment by mwvolo** [comment]
Hi @jivey - circling back around to see if you have anytime to work on this in the next couple weeks. No rush, just looking to get it on the roadmap. Thanks!

**Comment by jivey** [comment]
@mwvolo Hi and yes! I was a bit sidetracked with a hotfix but things are looking a lot better now. My plan is fully focus on this by Friday.

**Comment by jivey** [comment]
@mwvolo Hi Michael, a quick question as I get going on this. Does the "Books of interest" wording for the book selector still make sense with these additions? I wonder if there is a mismatch with the new questions assuming current textbook use.

**Comment by jivey** [comment]
@mwvolo When you said it would replace "Books you've used in your courses" does that mean just changing the question to "Which textbook(s) are you currently using?" or that you want to provide the visual book selector? I'm building off the current auto-complete selector for now, just want to make sure I plan things if you want a larger change to the visual selector:
![image](https://github.com/openstax/accounts/assets/34174/21c03218-f162-4c8c-bf1d-41ea14685d4e)

**Comment by mwvolo** [comment]
For now, we can continue to use the selector that we already have on that form - no need to change to the visual selector.

**Comment by jivey** [comment]
Quick update on my progress -- I've got the frontend work probably 90% there, I still need to fix a validation bug and add some helper text to the first question. Backend work is still in progress, but so far has been going quick. Hoping early next week to have a PR ready to look at.

**Comment by mwvolo** [comment]
Thanks for the update! I know that FE code is a bit of a disaster, thank you so much for taking your time and expertise to get this done!
