### ISSUE TITLE
StudyEdge errors on account login when using Google

### ISSUE THREAD

**Issue by mwvolo** [openstax/accounts#1191]
StudyEdge is using our accounts platform to log people in, which is working fine except when trying to authenticate with Google.

This [card](https://github.com/openstax/unified/issues/2333) might be related.

**Comment by Dantemss** [comment]
I was looking at the old card you linked. Did anything actionable end up coming out of this? Should we close the old card?

**Comment by mwvolo** [comment]
Nothing came out of this, I don't think I could reproduce it (outside the StudyEdge app - which is defunct).
I'd say we could close both of these cards unless there is something related to what you're talking about on the other card re: google auth in general that we need to address.

**Comment by Dantemss** [comment]
Closing since StudyEdge is gone and I haven't heard about Google complaining about this anymore.
