### ISSUE TITLE
Take down old accounts page

### ISSUE THREAD

**Issue by erikayvonne** [openstax/accounts#1200]
Chris was googling `openstax accounts` looking for the github repo and the top hit was this page: https://pages.openstax.org/accounts 

We'll need to find a way to take this down as it's pretty outdated.

The code (when inspecting the page) has references to [Tatsu](https://tatsubuilder.com/) which is a WordPress page builder. @edwoodward has asked devops if they can tell where it lives from the DNS entry.

### acceptance criteria

- [ ] ensure pages.openstax.org/accounts is not the top search result
- [ ] redirect https://pages.openstax.org/accounts to the homepage (https://openstax.org/)
- [ ] ensure pages.openstax.org/accounts isn't accessible to end users

**Comment by RoyEJohnson** [comment]
> Jemel Agulto
>   [1 year ago](https://openstax.slack.com/archives/C0HNULR42/p1654275672320769?thread_ts=1654270287.042219&cid=C0HNULR42)
> Idk where it's hosted, I think optidge developed it (edited) 
> 
> 
> Lindsay Josephs (she/her)
> :palm_tree:  [1 year ago](https://openstax.slack.com/archives/C0HNULR42/p1654276636514349?thread_ts=1654270287.042219&cid=C0HNULR42)
> I couldn't find it in the CMS
> 
> 
> Dani Nicholson
>   [1 year ago](https://openstax.slack.com/archives/C0HNULR42/p1654276646356489?thread_ts=1654270287.042219&cid=C0HNULR42)
> Ok, I’ve asked Optidge

**Comment by erikayvonne** [comment]
@DominiqueShu still needs to review analytics for this page, but the page itself is no longer needed.

**Comment by edwoodward** [comment]
Requested DNS change to point URL to our home page.

**Comment by edwoodward** [comment]
Created PR in bit-deployment to redirect pages.openstax to the home page. A DNS change will be needed to point pages.openstax.org to openstax.org once the deployment is released.

**Comment by erikayvonne** [comment]
targeting 10/4 release.
