### ISSUE TITLE
Show the privacy notice to users when logging in from all sites

### ISSUE THREAD

**Issue by mwvolo** [openstax/accounts#1214]
The new privacy notice is not being displayed; users are logging into accounts and being immediately redirected to another site.
An example would be logging into openstax.org, and then being sent directly to the site instead of agreeing to the new privacy notice.

**Acceptance criteria**

- [ ] Users are required to acknowledge a change in privacy notice when logging in from openstax.org

**Comment by brittanyearly** [comment]
On staging, when logging in, the notice appeared, already scrolled to the bottom, not starting at the top. Additionally, the check box did not need to be checked to submit and accept.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
