### ISSUE TITLE
Update leads from Salesforce to accounts

### ISSUE THREAD

**Issue by mwvolo** [openstax/accounts#1215]
When a lead is rejected in Salesforce, they remain as pending_verification in Accounts. This causes confusion on user numbers and doesn't allow us to properly handle or delete data that might be stale in our systems.

Note: Currently, this is not set to run automatically (want to verify how well it works in the production system before setting it up on cron), so it will need to manually run for verification it's working.

**Acceptance criteria**

- [ ] If a lead is sent to Salesforce for review, then rejected, it should reflect that in Accounts

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Closing as complete.
