### ISSUE TITLE
Google Login results in blank page

### ISSUE THREAD

**Issue by edwoodward** [openstax/accounts#123]
I logged in from dev.cnx.org using my Google account.  After logging into Google and entering the code for 2 step authentication, I got a blank white page instead of being directed to complete my account or at least redirected back to dev.cnx.org. 
Screenshot of page
![screenshot from 2015-02-04 06 54 22](https://cloud.githubusercontent.com/assets/1394695/6040748/0c651308-ac3b-11e4-8e52-6e9820daa2bb.png)

**Comment by Dantemss** [comment]
I think Ross's stuff was working, so this is probably a different error.

**Comment by Dantemss** [comment]
Will investigate after Sprint 6.

**Comment by edwoodward** [comment]
Some devs on CNX can log in with Facebook and others cannot.  It is not a consistent problem for all users, just some.  The users that have an issue cannot log in even with several attempts.

**Comment by karenc** [comment]
JP and Dante said it's possibly because there's already an account using the same email address.  Perhaps something like you already have a local account with your email address but your google login also use your email address.

They think it's fixed, just not sure if it's been deployed to the QA accounts that dev.cnx.org is using.

**Comment by Dantemss** [comment]
I think Ed got the error after it was fixed for Ross? Not entirely sure though.

**Comment by karenc** [comment]
QA accounts is up to date and it's still not working for me.  I've been getting the exception emails "[Accounts Exception] sessions#callback (IllegalState) "IllegalState"" whenever I try to login with my google account.

**Comment by Dantemss** [comment]
Yep, I see them too. Still broken.

**Comment by edwoodward** [comment]
Dante is correct, I did get the blank page after it was working for Ross.

**Comment by karenc** [comment]
It's working for me now.

**Comment by karenc** [comment]
But it's still broken for Ed.

**Comment by karenc** [comment]
It's working for Ed now :D
