### ISSUE TITLE
Facebook login results in blank page

### ISSUE THREAD

**Issue by edwoodward** [openstax/accounts#124]
I logged in from dev.cnx.org using Facebook.  I entered my Facebook id and password and a blank white page was displayed.

Screenshot of blank page
![screenshot from 2015-02-04 07 00 20](https://cloud.githubusercontent.com/assets/1394695/6040820/b696bb1a-ac3b-11e4-9c0f-b029c494a7b6.png)

**Comment by Dantemss** [comment]
Likely same cause as https://github.com/openstax/accounts/issues/123, whatever it is.

**Comment by edwoodward** [comment]
Some devs on CNX can log in with Facebook and others cannot.  It is not a consistent problem for all users, just some.  The users that have an issue cannot log in even with several attempts.

**Comment by karenc** [comment]
It's working for Ed now.

**Comment by jpslav** [comment]
woohoo!
