### ISSUE TITLE
Error page

### ISSUE THREAD

**Issue by Dantemss** [openstax/accounts#126]
An error page (oops, we messed something up) would be nice instead of a blank page.

**Comment by jpslav** [comment]
The blank pages Dante is referring to were either on Exercises or were reached through an error that has since been fixed.  But we should still have better (custom) error pages instead of the Rails defaults (i.e. we should have be using the layout, nice styles, exception ID numbers, etc.

**Comment by Dantemss** [comment]
This refers to production specifically (well, qa) so it should be the static public/500.html page

Maybe the rescue_from_exception block is misbehaving.

**Comment by karenc** [comment]
Error pages added in #151
