### ISSUE TITLE
Investigate email exceptions

### ISSUE THREAD

**Issue by Dantemss** [openstax/accounts#127]
Most likely the SendMessage routine is ignoring the SES settings because it uses the Mail gem directly instead of using a Rails mailer.

**Comment by karenc** [comment]
According to `config/secret_settings.yml`, accounts is using localhost port 25 for smtp.  There's nothing running on port 25 `netstat -alnp | grep LISTEN`.  Postfix, exim, sendmail are not installed.  So I think mail is just not set up.

**Comment by karenc** [comment]
The accounts QA server is using the Amazon SES HTTP API to send mail, so it's not using smtp.

There are 2 initializers for mail: https://github.com/openstax/accounts/tree/master/config/initializers/amazon_ses.rb and https://github.com/openstax/accounts/tree/master/config/initializers/mail.rb.  Additional mail configuration is in the environment files, e.g. https://github.com/openstax/accounts/tree/master/config/environments/production.rb.

I was able to send an email using the `SiteMailer` from `rails console`:
```ruby
irb(main):002:0> SiteMailer.delivery_method
=> :ses
irb(main):003:0> SiteMailer.mail(subject: 'test with ses as delivery method', to: 'karen@e-mail-tester.appspotmail.com', body: 'test email body').deliver
=> #<Mail::Message:36788880, Multipart: false, Headers: <Date: Mon, 23 Feb 2015 14:56:18 +0000>, <From: noreply@openstax.org>, <To: karen@e-mail-tester.appspotmail.com>, <message-id: 0000014bb6f12708-f90cf8a3-1339-4d74-8fd9-a7f1d1361a6e-000000@email.amazonses.com>, <Subject: [OpenStax] test with ses as delivery method>, <Mime-Version: 1.0>, <Content-Type: text/plain>, <Content-Transfer-Encoding: 7bit>>
```

I got the email:

```
Date: Mon, 23 Feb 2015 14:57:12 +0000
From: noreply@openstax.org
To: karen@e-mail-tester.appspotmail.com
Message-ID: <0000014bb6f12708-f90cf8a3-1339-4d74-8fd9-a7f1d1361a6e-000000@us-west-2.amazonses.com>
Subject: [OpenStax] test with ses as delivery method
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
X-SES-Outgoing: 2015.02.23-54.240.27.123
Feedback-ID: 1.us-west-2.oVlp8PEgkREbSg958fsBR0qgvE+aOYfJpj2ebF8cZ4I=:AmazonSES

test email body
```

**Comment by jpslav** [comment]
Yes, we just use the aws-ses gem (which uses the API); at least that's the intent.

**Comment by karenc** [comment]
So this can be closed?  What was the exception?

**Comment by Dantemss** [comment]
Accounts has an API to send messages in behalf of other apps.
