### ISSUE TITLE
SecurityTransgression raised by Doorkeeper

### ISSUE THREAD

**Issue by pumazi** [openstax/accounts#148]
I attempted to access doorkeeper (//{host}/oauth/applications/new) with a non-admin user, instead of a health 403 or something similar, I got a traceback. At first I didn't realize I was using a non-admin user, so I was trying to track down the source of the error, because I thought the application did something wrong.

I guess I would have expected a 403 forbidden page rather than an error. Thoughts?

**Comment by edwoodward** [comment]
There should not be a traceback since it will give someone trying for 
unauthorized access information they might be able to use.

**Comment by jpslav** [comment]
We need to put the error page infrastructure in for our nonstandard errors. I think there's an issue. We have code in other apps we can use.

**Comment by lakshmivyas** [comment]
The traceback is only in development configurations.  On production environments, you see a blank page.  The blank page should be replaced by something more helpful once we implement JP's suggestion above.

**Comment by jpslav** [comment]
Was this on a local dev instance or one of the deployed instances?

**Comment by jpslav** [comment]
that it is a blank page in production is somewhat unexpected as standard rails error pages should be kicking in.

**Comment by Dantemss** [comment]
Something is not configured properly probably, because https://github.com/openstax/accounts/issues/126

**Comment by karenc** [comment]
Is this fixed now that we have error pages?

**Comment by Dantemss** [comment]
Should be fixed. You will still get a backtrace in dev (local) but we won't change that.

**Comment by Dantemss** [comment]
Please close if this is solved or let us know otherwise.
