### ISSUE TITLE
Where do I change my password?

### ISSUE THREAD

**Issue by pumazi** [openstax/accounts#149]
I'm trying to change my password. There doesn't appear to be an interface for this. We should probably have one though, no?

**Comment by Dantemss** [comment]
Definitely. We just need a link to the /profile page, probably in the layout (though you are not REALLY supposed to stay on Accounts for too long).

**Comment by karenc** [comment]
There's a tab on the profile page for changing the password:

![change-password](https://cloud.githubusercontent.com/assets/153353/12682331/7381d8ca-c678-11e5-98cc-3f80f3203744.jpg)
