### ISSUE TITLE
Optimize user importer

### ISSUE THREAD

**Issue by Dantemss** [openstax/accounts#152]
Currently importing 40,000 users is very tedious and takes about half an hour...
An easy optimization would be to wrap the entire importer in 1 transaction, which would shorten the import time by a lot.

**Comment by Dantemss** [comment]
Should also check for user existence before importing (and if they exist, update the existing record).

**Comment by cnuber** [comment]
we need to have another unique identifier in addition to username, as in my testing there was a 'bob' user from the CNX import and a 'bob' user already in place in accounts.  We don't wanna overwrite existing users if they're different.

**Comment by Dantemss** [comment]
This is a whole other can of worms...

**Comment by lakshmivyas** [comment]
@Dantemss , @cnuber :  We may need this to be prioritized as this is causing a lot of issues when testing.   Any thoughts on using: https://github.com/tilo/smarter_csv?

Also, is it possible for import users routine to be smarter about previous runs? (Perhaps by creating a file "imported_users.info" file with details about the last import?

**Comment by jpslav** [comment]
do we really need to import all CNX users on each build of dev/qa/stage?  This import routine was written to be run once in production (and maybe once in stage to make sure it works).  Do we really need all 40k users to be able to do testing?

**Comment by gregfitch** [comment]
...and if the DB bites the dust at some point...

**Comment by lakshmivyas** [comment]
@jpslav - we need this on qa, stage and production.   While it may not be used once CNX is released, we are rebuilding servers quite frequently (with DB upgrade etc.,) and there have been instnaces where the import has taken servers out of commission.

Also, if we can optimize this import, we have a pattern that we can follow for future imports.

**Comment by karenc** [comment]
Now that we added a transaction around the whole thing, does it mean we won't have partially imported the users csv file?  Does this mean we don't have to make the script smarter about previous imports?

Anyway, there is already a result csv file called `import_users_results.csv`.  It should look something like this:

```
row_number,old_username,new_username,errors
1,karenchan,karenchan,User #<ActiveRecord::RecordInvalid: Validation failed: Username has already been taken>
2,user10,user10,User #<ActiveRecord::RecordInvalid: Validation failed: Username has already been taken>
3,user11,user11,""
4,user4,user4,""
5,user5,user5,""
6,user6,user6,""
7,user7,user7,""
8,user8,user8,""
9,user9,user9,""
10,username,username,""
11,yonaga,yonaga,""
```

I hope this helps.  I'll try to improve my script and code more.

**Comment by lakshmivyas** [comment]
@karenc - Awesome.  Did this also improve memory issues?   The major problem with the import task is servers running out of memory.

The import_user_results.csv looks useful.  It would help if info about when the last user import run was also available (perhaps as part of the file name?)

**Comment by karenc** [comment]
Yeah actually that's a good idea.  I'm going to include a timestamp in the import_user_results.csv filename.  I *think* I found where the memory issue is.  I'm going to try to test it.

**Comment by karenc** [comment]
An example output filename: `import_users_results.2015-03-20T15:05:32Z.csv`

**Comment by Dantemss** [comment]
With the transaction in place, making the importer smart would only be needed if we had to do multiple imports to, say, update the users.

**Comment by karenc** [comment]
Having only one transaction for all the users increased the memory usage by a lot.  So changed the code to have one transaction per 1000 (configurable) users.

The benchmarks are as follows:

|                  | Original   | No transaction | One transaction | Multiple transactions |
| ---------------  | ----------:| --------------:| ---------------:| ---------------------:|
| **Time (real)**  |            |                |                 |                       |
| 4000 users       |  6m52.556s |       8m8.919s |       3m17.362s |             2m50.438s |
| 10000 users      | 18m11.743s |     18m48.104s |      11m23.677s |              8m4.523s |
| **Memory (rsz)** |            |                |                 |                       |
| 4000 users       |   89.132MB |       10.128MB |       18.2220MB |              59.080MB |
| 10000 users      |  207.560MB |       14.704MB |       451.980MB |              65.008MB |

**Comment by lakshmivyas** [comment]
@karenc - Fantastic analysis. Excellent.

Removing the result hashtable probably helped a great deal.

Since we are already chunking users, would using https://github.com/tilo/smarter_csv benefit us even more?    Their case study says that they went from 7+ hours to 3 minutes.

Using smart csv means, we chunk the read & chunk the write - should make the code a lot nicer too.

That said,  I think this should already take us ashore as the memory usage is not ballooning between 4000 and 10000 users.

**Comment by karenc** [comment]
@lakshmivyas using smarter_csv chunk size should simplify the code I think.  I was manually splitting the csv into chunks because I need to have one transaction per 1000 users.  I was actually rereading the csv file many times...  I'll change my code to use smarter_csv, thanks!
