### ISSUE TITLE
Cannot log in with Rice gmail account

### ISSUE THREAD

**Issue by amberwebb** [openstax/accounts#158]
If I try to log in to dev with my Rice gmail account, I get a blank page in accounts-qa1 instead of being redirected back to dev.cnx.org.

**Comment by lakshmivyas** [comment]
@amberwebb - Can you please try again?  I updated the accounts code on qa1.

**Comment by amberwebb** [comment]
@lakshmivyas I tried again got this message:

500 Internal Server Error
Hi there, something is wrong. An email has been sent to the development team.

**Comment by karenc** [comment]
I think the problem is yesterday we tried to re-import the cnx users without clearing the database.  Most likely @amberwebb's rice gmail account is still in the contact_infos table, but the user has been deleted.  The code doesn't expect that so we've got a 500 error.  I'm going to go in and delete the contact_infos that have no users.

**Comment by lakshmivyas** [comment]
@karenc  - Thanks.  If the stage server did not have any import issues (that is import succeeded without OOM), maybe CNX could point to stage?

**Comment by karenc** [comment]
@reedstrm will need to change the configuration on dev.cnx.org.

**Comment by amberwebb** [comment]
@karenc @lakshmivyas  Not sure what accounts instance beta.cnx.org is using, but I cannot login at all. Get this message:
Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.

**Comment by karenc** [comment]
It looks like the accounts configuration (specifically the app id and secret) on beta.cnx.org probably needs to be updated since accounts-qa1 was rebuilt.

**Comment by karenc** [comment]
I did the following on accounts-qa1:

```sql
accounts_qa=> SELECT COUNT(*) FROM contact_infos WHERE user_id NOT IN (SELECT id FROM users);
 count
-------
 44278
(1 row)

accounts_qa=> SELECT COUNT(*) FROM contact_infos;
 count
-------
 84883
(1 row)

accounts_qa=> DELETE FROM contact_infos WHERE user_id NOT IN (SELECT id FROM users);
DELETE 44278
```

@amberwebb you should be able to login now.

**Comment by amberwebb** [comment]
@karenc I can successfully login now. Thanks.
