### ISSUE TITLE
Must accept terms twice for redirect

### ISSUE THREAD

**Issue by edwoodward** [openstax/accounts#159]
I logged into dev.cnx.org as a CNX user and was asked to reset my password. After that I accepted the terms, but was not redirected back to dev.cnx.org.  I accepted the terms a second time and was redirected. I should only have to accept the terms once and be redirected.

**Comment by Dantemss** [comment]
This might be fixed here: https://github.com/openstax/accounts/pull/157 but hard to say for sure without more testing.

**Comment by edwoodward** [comment]
It is not fixed on accounts-stage1 as of today.
