### ISSUE TITLE
Less hacky way to determine that the user is coming from CNX

### ISSUE THREAD

**Issue by Dantemss** [openstax/accounts#167]
Now that we propagate the `@application` all the way to the login page, we can use that to determine if the user is coming from CNX, rather than checking the referer.

In `sessions#new`.

**Comment by jpslav** [comment]
FWIW, the client_id is set from Tutor when users arrive from Tutor, and it is now stored in the session.

**Comment by Dantemss** [comment]
OBE because we don't have this CNX-only behavior anymore.
