### ISSUE TITLE
Remove user_id foreign key from Identity

### ISSUE THREAD

**Issue by jpslav** [openstax/accounts#173]
In reviewing some code, I saw that `Identity` `belongs_to :user`.  This seems strange to me because an identity is also accessible through a user's authentications (it may have zero or one authentications where the provider is 'identity').

Can we remove this foreign key?  Seems like having two sets of data to represent the same association can confuse future developers or lead them astray.

If we still want to be able to say `user.identity` or `identity.user` I think we can just make them methods that go through the authentication either using a `:through` association or just make methods:

``` ruby
class Identity < ActiveRecord::Base
  ...
  def user
    User.joins{authentications}.where{authentications.provider == 'identity'}
                               .where{authentications.uid == my{id.to_s}}
                               .first
  end
  ...
end

class User < ActiveRecord::Base
  ...
  def identity
    authentications.where{provider == 'Identity'}.first
  end
  ...
end
```

/cc @karenc @Dantemss @nathanstitt

**Comment by Dantemss** [comment]
Yes, please. Less duplication is better.
Another possible improvement that I noticed, but forgot to create an issue about, is to not special-case identity in our routines. Maybe it should be ok for an Identity to be created without a User and it should be handled just like other oauth providers in the SessionsCallback.
