### ISSUE TITLE
User is not redirected back to application after registering new account

### ISSUE THREAD

**Issue by edwoodward** [openstax/accounts#189]
I logged in using Twitter on accounts-stage1. I registered a new account and ended up on my profile after I completed the setup. When I do the same using accounts.openstax.org, I am redirected to beta.cnx.org after the setup.

**Comment by Dantemss** [comment]
Hello. It all depends on how you reached the login page. If you typed the url for accounts directly, we can't tell which app you came from.

**Comment by Dantemss** [comment]
I do agree that we need a solution that works for all apps, like trusted return url's.

**Comment by karenc** [comment]
I'm going to test this on master.  I think we've changed some redirection code recently.

**Comment by edwoodward** [comment]
In both tests, I accessed accounts via the login link on CNX

**Comment by karenc** [comment]
I just tried with webview, cnx-authoring and accounts, all at current master.  It worked for me:

1. Click on the login link.
2. On the accounts login page, click on the Twitter logo.
3. Login to twitter and authorize app.
4. Back on accounts, click on "Finish setting up my account".
5. Check "I have read the Terms of use..." and click "Register".
6. Back on webview.

**Comment by edwoodward** [comment]
I tried it again using a gmail and twitter account and could not recreate the problem I had earlier. Closing.

**Comment by Dantemss** [comment]
It does definitely happen in some corner cases though... Like typing the address to accounts or having multiple tabs open (maybe).
