### ISSUE TITLE
undefined method `password_expired?` in IdentitiesController

### ISSUE THREAD

**Issue by jpslav** [openstax/accounts#259]
Got a couple of exceptions with:

```
A NoMethodError occurred in identities#reset_password:

  undefined method `password_expired?' for nil:NilClass
  app/controllers/identities_controller.rb:40:in `reset_password'
```

That offending line:

```ruby
    if !current_user.is_anonymous? && current_user.identity.password_expired?
```

The `current_user` isn't anonymous but `current_user.identity` is `nil` (an "identity" is a password authentication in Accounts).  

I would recommend [adding a spec here](https://github.com/openstax/accounts/blob/master/spec/features/reset_password_spec.rb).  The `create_user` call [at the top of that file](https://github.com/openstax/accounts/blob/master/spec/features/reset_password_spec.rb#L5) creates a dummy user with an identity, so you'll need to find a way to either create a non-anonymous user without an identity (maybe as an option to that `create_user` method) or have an option to add a non-identity authentication (probably some examples somewhere else of creating a user with a fake Facebook authentication).  

Users are sent to this reset password page [when their password expires](https://github.com/openstax/accounts/blob/ffc70e83754a7e44355448a5355a6f5617f3a30e/config/initializers/controllers.rb#L56).  And those people of course have identities.  So these must be some random arrivals.  A reasonable behavior for when a password-less person goes to reset_password would be to redirect them to the login page with a flash error that says "Your password cannot be reset.  Please contact support for assistance." -- just in case they are not some random arrival and have a real need, we won't lose them.

**Comment by jpslav** [comment]
In addition to reaching this from the expired password approach, these could also be users with social logins who say "Forgot password"

**Comment by Dantemss** [comment]
Most definitely. Make sure the message tells them to try FB/Google/Twitter. Or even figure out which one they have.
