### ISSUE TITLE
sessions#callback (IllegalState) "IllegalState"

### ISSUE THREAD

**Issue by jpslav** [openstax/accounts#261]
See the exception emails titled: `[Accounts] (prodtutor) sessions#callback (IllegalState) "IllegalState"`.  This probably needs @Dantemss, @karenc, or @jpslav to diagnose.  @Dantemss had some thoughts on the Jan 14 email.

**Comment by Dantemss** [comment]
As far as I can tell, on the latest occurrence the user had a google oauth2 account and tried to login with his facebook instead (which most likely had the same email address). However, I was not able to reproduce the error with my own google/fb.

**Comment by Dantemss** [comment]
Seems fixed.
