### ISSUE TITLE
Bug: Accounts 500 error for bad login attempts

### ISSUE THREAD

**Issue by BryanEliDimas** [openstax/accounts#615]
When someone enters an incorrect username or e-mail address, Accounts generates a 500 error due to a Nil value.

**Comment by BryanEliDimas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: Accounts 500 error for bad login attempts](https://trello.com/c/PMX0vmZR/890-bug-accounts-500-error-for-bad-login-attempts)

**Comment by Dantemss** [comment]
This seems to be solved
