### ISSUE TITLE
No new Accounts PRs can build on Travis

### ISSUE THREAD

**Issue by RoyEJohnson** [openstax/accounts#665]
## Description
Some packages have been deprecated and there are security warnings in https://github.com/openstax/accounts/network/alerts

I have tried to update packages, but the builds still fail
```
     Selenium::WebDriver::Error::UnknownError:
       unknown error: Chrome failed to start: exited abnormally
         (unknown error: DevToolsActivePort file doesn't exist)
         (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```
[chromedriver-helper](https://github.com/flavorjones/chromedriver-helper/issues/83) is also deprecated. I don't know how it is used, so I have no idea where to start in trying to replace it (the page recommends using [webdrivers](https://github.com/titusfortner/webdrivers).)

## Acceptance

At least some PRs build successfully on Accounts 

## PRs
https://github.com/openstax/accounts/pull/666

**Comment by BryanEliDimas** [comment]
PR is ready for code review.
