### ISSUE TITLE
Adding contact info doesn't send verification message

### ISSUE THREAD

**Issue by jpslav** [openstax/accounts#81]
The documentation for the API endpoint for creating new `ContactInfo`s [says][1]:

    Lets a caller create a new unverified ContactInfo.  The verification
    process will be started when this call successfully completes.

However, this doesn't actually happen.  There is a `SendContactInfoConfirmation` routine, but it isn't called.  The controller method should defer to a `ContactInfosCreate` handler that calls `CreateContactInfo` routine, one job of which is to call `SendContactInfoConfirmation` if necessary.

Hopefully `lev` is now good to go re using handlers in API controller actions; if not, the controller action can at the least call a `CreateContactInfo` routine directly.

[1]: https://github.com/openstax/accounts/blob/master/app/controllers/api/v1/contact_infos_controller.rb#L45

**Comment by Dantemss** [comment]
Fixed, since the ContactInfo API was removed and replaced with the profile page.
