### ISSUE TITLE
Allow users in other apps to create temporary users in accounts

### ISSUE THREAD

**Issue by Dantemss** [openstax/accounts#89]
The API call will work like this:

- It requires a (full) name and an email address.
- It will check if the email address already exists.
  - If the email does not exist, a new user marked as temporary is created. Any user who can verify the email address can claim that account. When the account is claimed, the user is asked to authorize his apps again (unless the apps are trusted).
  - If the email does exist and the application is trusted, the app is given automatic access to that user's account.
- In both cases the user is returned by the API call.

**Comment by Dantemss** [comment]
This issue will likely be solved when we implement the API that lets tutor admins create accounts for teachers/students. This can just be an extra option on that API.

**Comment by nathanstitt** [comment]
Users have a `is_temp` field, which is set to true when a user is first created. I'm not entirely sure what the purpose of the field is, but it looks like a way to create users and then have them accept terms and conditions before they can access systems.

I see that it's consulted in the sessions callback to decide if the account should be deleted and it's information transferred to a real account in [sessions_callback.rb#L78-L87](https://github.com/openstax/accounts/blob/master/app/handlers/sessions_callback.rb#L78-L87) The [user_access_policy.rb#L8-L16](https://github.com/openstax/accounts/blob/master/app/access_policies/user_access_policy.rb#L8-L16) also disallows access by temp users.

What I'm currently unclear on is whether the `is_temp` attribute is sufficient for the purposes of this request.  Most likely it's semantics are subtly different in some way?

If the current `is_temp` won't get us what we need, we could also replace the attribute with a `state` field that would allow `:temp` and `:pending` values.  We could then add a `is_temp?` method to Accounts to continue to provide the current behavior.

**Comment by Dantemss** [comment]
Seems done to me...
