### ISSUE TITLE
Creating Duplicate accounts with the same email

### ISSUE THREAD

**Issue by khannum19** [openstax/accounts#921]
A student has 1 confirmed Student account (created 2-13-20) and 2 unconfirmed accounts (created 10-23-20). All 3 accounts are connected to the same email. Somehow, the student was able to create a new account with an email address already confirmed in the system and was not blocked by the email already in use message. 

(The 2 unconfirmed accounts appear to be connected to the PIN issue where accounts are created with an unconfirmed email instead of being sent to Preauth. I have since closed the duplicate accounts for this user to help with login).

Student email: kwright1243@student.egcc.edu
Confirmed account: UUID: e7ab5881-82c0-48a7-9768 (423980)  - Created 2-13-20
Unconfirmed accounts:  UUID: bace4028-bcbd-4ac2-b4f5-09b7494d7a67 (821213),  UUID: bdc7590a-3341-4af3-ade1-2d58976c83cf (821218) - both accounts created 10-23-20.

Case 56858

A picture of the accounts is attached. I've had issues with ZenHub attachments in the past, so please let me know if you have any issues opening the image. ![Duplicate Account.PNG](https://images.zenhubusercontent.com/5cc356ae9c68a42e11d8a050/a5c12308-1040-4009-aeba-65346dad42c6)

**Comment by khannum19** [comment]
They listed the error as 322184, but that looks like maybe one of the 6 digit pins that wasn't working for them

**Comment by mwharrison** [comment]
Issue moved to [openstax/business-intel #1583](https://github.com/openstax/business-intel/issues/1583) via [**ZenHub**](https://www.zenhub.com/)
