### ISSUE TITLE
Educator accounts verified but no contact created from the faculty lead

### ISSUE THREAD

**Issue by bonnebbrown** [openstax/accounts#978]
We've been getting some instructors who say they have been verified but don't have access.
They receive a Sheerid email, their lead is converted by tracking user but they do not have a contact created, which leaves them without access to the instructor resources. 

Slack link for more details: https://openstax.slack.com/archives/C69BU01RC/p1628620921079400

Example 1, case 66723: 
Lead: https://openstax.lightning.force.com/lightning/r/Lead/00Q6f00001NADUrEAP/view
Account ID: 1063083
UUID: fc2770cc-f400-442c-a3b5-015ab20ded5b
Screenshot of email:
![2021-08-10_13-36-56.png](https://images.zenhubusercontent.com/5bad045177c9d97356bc41df/1f7cff48-f946-40d2-866c-92d9f60173ca)

Example 2, case 66578
Lead: https://openstax.lightning.force.com/lightning/r/Lead/00Q6f00001NAB24EAH/view
Account ID: 1062798
UUID:  0e9cd87f-cd50-45df-8c31-e370e8fae1e6

Example 3, case 66576
Lead: https://openstax.lightning.force.com/lightning/r/Lead/00Q6f00001O3FaCEAV/view
Account ID: 1066310
UUID: 0120a271-16ab-47d6-9a4a-0c64d402b7cb

**Comment by mwharrison** [comment]
@brittanyearly this might be hard to reproduce but I am pretty confident we will not see this behavior with the new way we are processing leads in accounts.

**Comment by brittanyearly** [comment]
Verified in Production.
